name: Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set version number
      run: echo "VERSION=$(expr ${{ github.run_number }} + 5908)" >> $GITHUB_ENV

    - name: Use version number
      run: echo $VERSION

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Packages
      run: nuget restore Oxide.Rust.sln

    - name: Build solution
      run: msbuild Oxide.Rust.sln -t:rebuild -property:Configuration=Release

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Oxide.*.zip
        tag_name: 2.0.${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          See https://umod.org/games/rust for changes