name: Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Increment version
      uses: action-pack/increment@v2
      with:
        name: 'VERSION'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log repository variables
      run: |
        echo "GITHUB_REF_NAME=$env:GITHUB_REF_NAME"
        echo "VERSION=$env:VERSION"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Packages
      run: nuget restore Oxide.Rust.sln

    - name: Build solution
      run: msbuild Oxide.Rust.sln -t:rebuild -property:Configuration=Release
      
    - name: Create artifact bundles
      run: |
        New-Item "src\bin\Artifact" -ItemType Directory -Force | Out-Null
        Get-ChildItem "src\bin\Bundle" -Directory | ForEach-Object {
            $artifact = $($_.Name)
            if ($env:GITHUB_REF_NAME -ne "master") {
                $artifact = $($_.Name) + "-$env:GITHUB_REF_NAME"
            }
            Compress-Archive -Path ".\src\bin\Bundle\$($_.Name)\*" -DestinationPath "src\bin\Artifact\$artifact.zip"
        }

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/bin/Artifact/Oxide.*.zip
        tag_name: 2.0.${vars:VERSION}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          See https://umod.org/games/rust for changes