name: Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Increment version number
      env:
        NUM: ${{ github.run_number }}
      run: |
        echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+5901))
    
    - run: echo "$GITHUB_CONTEXT" 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Packages
      run: nuget restore Oxide.Rust.sln

    - name: Build solution
      run: msbuild Oxide.Rust.sln -t:rebuild -property:Configuration=Release

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Oxide.*.zip
        tag_name: 2.0.${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          See https://umod.org/games/rust for changes