name: Build Solution

on:
  workflow_call:
    inputs:
      branch-postfix:
        required: false
        type: string

jobs:
  build:
    name: Build Oxide Solution
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Increment version
        uses: action-pack/increment@v2
        with:
          name: "VERSION"
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore Oxide.Rust.sln

      - name: Build solution
        run: msbuild Oxide.Rust.sln -t:rebuild -property:Configuration=Release -property:Version=2.0.${{ vars.VERSION }}${{ inputs.branch-postfix }}

      - name: Zip bundles
        run: |
          cd src\bin\Bundle
          7z a Oxide.Rust.zip Oxide.Rust
          7z a Oxide.Rust-linux.zip Oxide.Rust-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oxide-bundles
          path: src\bin\Bundle\Oxide.*.zip
