name: Build and Upload Bundles to S3

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Run Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      branch-postfix: "-${{ github.ref_name }}"

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: oxide-bundles
          path: artifacts
      - name: Deploy to Cloudflare R2
        run: |
          aws s3 sync artifacts s3://oxide-downloads/artifacts/rust/${{ github.ref_name }} --endpoint-url https://6ca34792c7e62e96e8088efe1ee92052.r2.cloudflarestorage.com/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET }}
          AWS_DEFAULT_REGION: auto
